### ISSUE TITLE
冗長部分の改修

### ISSUE THREAD

**Issue by machanet** [ag113ate/gattsuri_gourmet_site#1]
https://github.com/ag113ate/gattsuri_gourmet_site/blob/97bbdbd1ce1736b57db8ee8ed424f0e41a44fef9/app/views/gourmet_sites/disp_search_result.html.erb#L171-L187

上記部分のコードで同じ記述を二度繰り返しているので、別の書き方に変更する。

**Comment by ag113ate** [comment]
それぞれ異なるイベント処理のため、冗長的な処理はありません。
よって、現状のコードで問題ありません。
